INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Alice', 'Johnson', 'alice.johnson@example.com', 'New York');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Bob', 'Smith', 'bob.smith@example.com', 'Los Angeles');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Charlie', 'Brown', 'charlie.brown@example.com', 'Chicago');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Diana', 'Prince', 'diana.prince@example.com', 'Washington DC');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Eve', 'Adams', 'eve.adams@example.com', 'San Francisco');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Frank', 'Miller', 'frank.miller@example.com', 'Boston');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Grace', 'Davis', 'grace.davis@example.com', 'Seattle');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Henry', 'Wilson', 'henry.wilson@example.com', 'Austin');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Ivy', 'Garcia', 'ivy.garcia@example.com', 'Denver');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Jack', 'Martinez', 'jack.martinez@example.com', 'Miami');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Kate', 'Rodriguez', 'kate.rodriguez@example.com', 'Phoenix');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Liam', 'Lopez', 'liam.lopez@example.com', 'Portland');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Mia', 'Gonzalez', 'mia.gonzalez@example.com', 'Nashville');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Noah', 'Perez', 'noah.perez@example.com', 'Salt Lake City');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Olivia', 'Torres', 'olivia.torres@example.com', 'Raleigh');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Parker', 'Flores', 'parker.flores@example.com', 'Oklahoma City');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Quinn', 'Rivera', 'quinn.rivera@example.com', 'Albuquerque');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Ryan', 'Gomez', 'ryan.gomez@example.com', 'Colorado Springs');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Sophia', 'Diaz', 'sophia.diaz@example.com', 'Tucson');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Tyler', 'Morales', 'tyler.morales@example.com', 'Fresno');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Uma', 'Ortiz', 'uma.ortiz@example.com', 'Sacramento');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Victor', 'Gutierrez', 'victor.gutierrez@example.com', 'Mesa');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Wendy', 'Chavez', 'wendy.chavez@example.com', 'Virginia Beach');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Xander', 'Ramos', 'xander.ramos@example.com', 'Atlanta');
INSERT INTO employees (first_name, last_name, email_id, location) VALUES ('Yara', 'Hernandez', 'yara.hernandez@example.com', 'Kansas City');
